language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower
  - bower install
  - psql -c 'create database "cityHacker_test";' -U postgres
  - NODE_ENV=test ./node_modules/.bin/knex migrate:latest
matrix:
  allow_failures:
    - node_js: '0.11'
